version: '3'
services:
  wallet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/account_abstraction
      REDIS_HOST: redis
    command: ["/bin/sh", "-c", "npm run db-migrate && npm run dev"]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: account_abstraction
    restart: always
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: